/*
 * This file is part of CodeCadenza, a set of tools, libraries and plug-ins
 * for modeling and creating Java-based enterprise applications.
 * For more information visit:
 *
 * https://github.com/codecadenza/
 *
 * This software is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */
package net.codecadenza.eclipse.generator.facade.method;

import net.codecadenza.eclipse.generator.boundary.method.AddToAssociationBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.BasicBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.ChangeAssociationBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.ChangeParentBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.ChangePasswordBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.CopyBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.CountBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.DownloadBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.FindAllBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.FindByParentBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.FindByUniqueKeyBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.GetListOfValuesBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.LogOnBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.RemoveFromAssociationBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.SearchBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.SearchByUniqueKeyBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.boundary.method.UploadBoundaryMethodGenerator;
import net.codecadenza.eclipse.generator.common.AbstractJavaSourceGenerator;
import net.codecadenza.eclipse.model.boundary.BoundaryMethod;
import net.codecadenza.eclipse.model.boundary.BoundaryMethodTypeEnumeration;

/**
 * <p>
 * Factory for facade method generators
 * </p>
 * <p>
 * Copyright 2025 (C) by Martin Ganserer
 * </p>
 * @author Martin Ganserer
 * @version 1.0.0
 */
public class FacadeMethodGeneratorFactory {
	/**
	 * Private constructor
	 */
	private FacadeMethodGeneratorFactory() {

	}

	/**
	 * @param method
	 * @param parentGenerator
	 * @return a generator for the given method. It will return null if a method should not be generated by this service!
	 */
	public static BasicBoundaryMethodGenerator getMethodGenerator(BoundaryMethod method,
			AbstractJavaSourceGenerator parentGenerator) {
		final var utility = new FacadeMethodGeneratorUtility(method);

		if (method.getMethodType() == BoundaryMethodTypeEnumeration.SEARCH_BY_FILTER)
			return new SearchByFilterFacadeMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.SEARCH)
			return new SearchBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.UPDATE)
			return new UpdateFacadeMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.FIND_BY_PARENT)
			return new FindByParentBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.GET_LIST_OF_VALUES)
			return new GetListOfValuesBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.COUNT)
			return new CountBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.CREATE)
			return new CreateFacadeMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.FIND_ALL)
			return new FindAllBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.CHANGE_PARENT)
			return new ChangeParentBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.LOG_ON)
			return new LogOnBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.DOWNLOAD)
			return new DownloadBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.UPLOAD)
			return new UploadBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.ADD_TO_ASSOCIATION)
			return new AddToAssociationBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.REMOVE_FROM_ASSOCIATION)
			return new RemoveFromAssociationBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.DELETE)
			return new DeleteFacadeMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.CHANGE_PASSWORD)
			return new ChangePasswordBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.COPY)
			return new CopyBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.SEARCH_BY_UNIQUE_KEY)
			return new SearchByUniqueKeyBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.FIND_BY_UNIQUE_KEY)
			return new FindByUniqueKeyBoundaryMethodGenerator(method, utility, parentGenerator);
		else if (method.getMethodType() == BoundaryMethodTypeEnumeration.CHANGE_ASSOCIATION)
			return new ChangeAssociationBoundaryMethodGenerator(method, utility, parentGenerator);

		return null;
	}

}
